#!/usr/bin/env python3
"""ecbuild -- bundle an eliza/ template with its presets and (optionally) build + render it.

EffectCraft's script engine has no #include / $.evalFile, so this tool inlines every
`//@include "relative/path.jsx"` line of a template (recursively, each file once), prepends
ELIZA_ROOT + ELIZA_PARAMS, writes one self-contained .jsx bundle, then can run:

    effectcraft-cli script BUNDLE.jsx --save-as OUT.ecproj
    effectcraft-cli render OUT.ecproj --comp COMP --out OUT.mp4 --format h264 ...

Examples (from the repo root; Windows: `py` instead of `python3`, paths with / or \\ both fine):
    python3 eliza/tools/ecbuild.py eliza/templates/spiral_loop.jsx --set orientation=portrait --set seconds=8 \
        --save-as /tmp/spiral.ecproj --render /tmp/spiral.mp4 --comp SpiralLoop_Portrait
    python3 eliza/tools/ecbuild.py eliza/templates/showoff_20s.jsx --params my.json --bundle-only

Only uses the Python 3 standard library.
"""
import argparse, json, os, re, shutil, subprocess, sys
from pathlib import Path

ELIZA_DIR = Path(__file__).resolve().parent.parent
INCLUDE_RE = re.compile(r'^\s*//\s*@include\s+["\']([^"\']+)["\']\s*$')


def inline(path, seen, out):
    path = path.resolve()
    if path in seen:
        return
    seen.add(path)
    out.append(f"// ===== begin {path.relative_to(ELIZA_DIR.parent) if ELIZA_DIR.parent in path.parents else path} =====")
    for line in path.read_text(encoding="utf-8").splitlines():
        m = INCLUDE_RE.match(line)
        if m:
            inline(path.parent / m.group(1), seen, out)
        else:
            out.append(line)
    out.append(f"// ===== end {path.name} =====")


def parse_value(v):
    try:
        return json.loads(v)
    except ValueError:
        return v  # bare string


def find_cli(explicit):
    for c in (explicit, os.environ.get("EFFECTCRAFT_CLI"), shutil.which("effectcraft-cli")):
        if c:
            return c
    sys.exit("effectcraft-cli not found: pass --cli PATH, set EFFECTCRAFT_CLI, or put it on PATH")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("template")
    ap.add_argument("--params", help="JSON file with template parameters")
    ap.add_argument("--set", action="append", default=[], metavar="KEY=VALUE", help="override one parameter (VALUE is JSON or a bare string)")
    ap.add_argument("--bundle-out", help="where to write the bundle (default eliza/build/<template>.bundle.jsx)")
    ap.add_argument("--bundle-only", action="store_true", help="just write the bundle")
    ap.add_argument("--save-as", help="run the bundle and save the project here (.ecproj)")
    ap.add_argument("--render", help="render the saved project to this file")
    ap.add_argument("--comp", help="comp to render (required with --render)")
    ap.add_argument("--format", default="h264", help="render format (default h264; HEVC/AV1 encoders are immature)")
    ap.add_argument("--bitrate", default="16000")
    ap.add_argument("--audio", default="auto", choices=["auto", "on", "off"])
    ap.add_argument("--render-arg", action="append", default=[], help="extra arg passed to `render` (repeatable), e.g. --render-arg=--end --render-arg=8")
    ap.add_argument("--cli", help="path to effectcraft-cli (else $EFFECTCRAFT_CLI, else PATH)")
    a = ap.parse_args()

    tpl = Path(a.template)
    params = {}
    if a.params:
        params.update(json.loads(Path(a.params).read_text(encoding="utf-8")))
    for kv in a.set:
        k, _, v = kv.partition("=")
        params[k] = parse_value(v)

    body = []
    inline(tpl, set(), body)
    header = [
        "// GENERATED by eliza/tools/ecbuild.py -- edit the template / presets, not this file.",
        f"var ELIZA_ROOT = {json.dumps(ELIZA_DIR.as_posix())};",
        f"var ELIZA_PARAMS = {json.dumps(params)};",
    ]
    out = Path(a.bundle_out) if a.bundle_out else ELIZA_DIR / "build" / (tpl.stem + ".bundle.jsx")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(header + body) + "\n", encoding="utf-8")
    print(f"bundle: {out}")
    if a.bundle_only or not a.save_as:
        if a.render:
            sys.exit("--render needs --save-as")
        return

    cli = find_cli(a.cli)
    proj = Path(a.save_as).resolve()
    proj.parent.mkdir(parents=True, exist_ok=True)
    r = subprocess.run([cli, "script", str(out), "--save-as", str(proj)])
    if r.returncode != 0:
        # Quirk: a failed script still saves the half-built project. Remove it so nobody renders it.
        if proj.exists():
            proj.unlink()
            print(f"script failed -> removed half-built {proj}", file=sys.stderr)
        sys.exit(r.returncode)
    print(f"project: {proj}")
    if a.render:
        if not a.comp:
            sys.exit("--render needs --comp")
        dst = Path(a.render).resolve()
        dst.parent.mkdir(parents=True, exist_ok=True)
        cmd = [cli, "render", str(proj), "--comp", a.comp, "--out", str(dst), "--format", a.format,
               "--audio", a.audio, "--quality", "best"]
        if a.format in ("h264", "hevc", "av1", "webm"):
            cmd += ["--bitrate", a.bitrate]
        r = subprocess.run(cmd + a.render_arg)
        sys.exit(r.returncode)


if __name__ == "__main__":
    main()
